### ISSUE TITLE
[ember-intl] (...) missing from en-us

### ISSUE THREAD

**Issue by HenryVonfire** [jasonmit/ember-intl-cp-validations#12]
Using `ember-intl-cp-validations` in combination with the latest version of `ember-intl` (2.13.1), when the translation files aren't called `en-us`, some errors of missing keys are thrown in the console. [Here](https://github.com/HenryVonfire/intl-log) is a test project in which this can be reproduced.

**Comment by jasonmit** [comment]
Thanks, I was able to reproduce it and will have it fixed soon

**Comment by jasonmit** [comment]
2.3.1 should resolve this

**Comment by HenryVonfire** [comment]
@jasonmit Thanks for your effort :blush:
