### ISSUE TITLE
Pushing latest releases to npm (4.0.1)

### ISSUE THREAD

**Issue by lpaulger** [jasonmit/ember-intl-cp-validations#46]
The latest versions on npm is `3.0.1` (https://www.npmjs.com/package/ember-intl-cp-validations)

and it's a bit concerning that I can't even seen `3.0.1` in the tags section of this repo.

The reason I am opening this PR is due to a build warning I see:
> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: my-project -> ember-intl-cp-validations -> ember-cli-babel

**Comment by enkol** [comment]
@lpaulger The new version is published on npm as `@ember-intl/cp-validations`, instead of `ember-intl-cp-validations`.

**Comment by olleolleolle** [comment]
@lpaulger Does this resolve the issue?

**Comment by jasonmit** [comment]
@enkol is correct.

@olleolleolle yes as it's been upgrading to ember-cli-babel 6.

**Comment by lpaulger** [comment]
yes thank you for pointing this out, we were able to update correctly. Might be worth just adding a deprecation warning to the old npm package:

https://docs.npmjs.com/cli/deprecate.html

**Comment by jasonmit** [comment]
@lpaulger done, thanks for the heads up.
