### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by fsmanuel** [jasonmit/ember-intl-cp-validations#85]
Can we review and merge https://github.com/ember-intl/cp-validations/pull/84 and have a new release? That would remove quite some deprecations.

**Comment by fsmanuel** [comment]
@buschtoens @jasonmit can we release a new version?

**Comment by kennstenicht** [comment]
@buschtoens or @jasonmit, do either of you have time to review and release an new version? :pray:

**Comment by tehhowch** [comment]
@ijlee2 / @snewcomer ?

There's still a bunch of work to do for a 4.0 compatible release (see #82 ), but a release that gets this project off of ember-cli-babel v6 would be appreciated as a stepping stone.

(I definitely think we shouldn't require consuming apps to also be on ember-auto-import v2 in order to upgrade from ember-cli-babel v6, and therefore am in favor of multiple distinct version bumps, as that makes the upgrade process smoother.)

**Comment by jasonmit** [comment]
@fsmanuel I just sent an npm invite to add you to the org to help with versioning / unblocking you all.

**Comment by ijlee2** [comment]
@tehhowch Yeah, a couple of days ago, I tried to see if I could come up with an up-to-date pull request for @buschtoens' work, but didn't finish it (https://github.com/ember-intl/cp-validations/tree/update-project-new).

For the next month or so, I'm busy with a couple of things and won't be able to actively help with maintenance and release. If you can help us out, that'd be great.

**Comment by fsmanuel** [comment]
@jasonmit thanks. can you also give me access to the repo?

**Comment by fsmanuel** [comment]
I'm not sure if we should release as `v4.0.2` or `v5.0.0` here is the diff: https://github.com/ember-intl/cp-validations/compare/v4.0.1...main

Support for node versions `6.* || 8.*` were droped in https://github.com/ember-intl/cp-validations/commit/b5badd2e087c8f7499d52952ee68925f8d009832 so it's kind of a breaking change but as this node versions are pretty old I'm not sure. What do you think @tehhowch @ijlee2 @kennstenicht ?

**Comment by tehhowch** [comment]
> I'm not sure if we should release as `v4.0.2` or `v5.0.0` here is the diff: https://github.com/ember-intl/cp-validations/compare/v4.0.1...main
> 
> Support for node versions `6.* || 8.*` were droped in https://github.com/ember-intl/cp-validations/commit/b5badd2e087c8f7499d52952ee68925f8d009832 so it's kind of a breaking change but as this node versions are pretty old I'm not sure. What do you think ?

Follow semver, release v5 

Note also that anyone who was using the `warn` method on the messages class will have to update their code, as that method was removed, too.

**Comment by fsmanuel** [comment]
Agreed! Thanks for the `warn` hint.

**Comment by fsmanuel** [comment]
Released `v5.0.0`

**Comment by fsmanuel** [comment]
@ijlee2 we never released v6 with the 4 PR above. Should I release v6?

**Comment by ijlee2** [comment]
Hi, @fsmanuel. I don't know much about details (haven't kept up with the changes), but am in favor of making new releases to allow progress. I'll ask Jan B. today for additional thoughts.

**Comment by ijlee2** [comment]
@fsmanuel Quickly looked at the file changes in #88 and #90, and think it'd be okay to release `v6` (either as a stable or as an alpha version first). I messaged Jan for possible feedback.

Currently, `.github/workflows/ci.yml` and `package.json` show that `@ember-intl/cp-validations` support Node 12, Node 14, Ember 3.24, and Ember 3.28. I wondered if you may already have a plan to deprecate supporting these LTS's, as they have met the end-of-life some time ago.

**Comment by fsmanuel** [comment]
@ijlee2 thanks for the feedback. I opend https://github.com/ember-intl/cp-validations/pull/99 to update ember-cli to v4.8 that drops support for node v12. I think we should merge that and then release v6 with the breaking changes (import name changed and node v12 is no longer supported).

**Comment by fsmanuel** [comment]
@ijlee2 I updated release-it: https://github.com/ember-intl/cp-validations/pull/101 and will cut a new release soon.

**Comment by fsmanuel** [comment]
@ijlee2 can we remove the branch protection again. Seems like I can no longer run `npx release-it`

**Comment by ijlee2** [comment]
@fsmanuel Yep, removed. I elevated your role to admin so that you can experiment with the repo settings.

**Comment by fsmanuel** [comment]
@ijlee2 That worked! Released [v6](https://github.com/ember-intl/cp-validations/releases/tag/v6.0.0)
